### ISSUE TITLE
关于Material Icons的一个显示问题

### ISSUE THREAD

**Issue by chiaki64** [MoeNetwork/MoeCDN-Universal-PHP#1]
将 //fonts.googleapis.com/icon?family=Material+Icons 的连接替换为 //cdn.moefont.com/fonts/icon?family=Material+Icons 后,所有的Material Icons 都不显示.
通过比对发现与 MoeFont 的 Material Icons ttf字体文件有关,测试过三台机器皆是如此,希望不是特例_(:3」∠)_

**Comment by kirainmoe** [comment]
http://fonts.gstatic.com/s/materialicons/v12/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2

格式不是 woff2 吗？(:3」∠)

**Comment by cuteSakuraHime** [comment]
Google http://fonts.gstatic.com/s/materialicons/v12/2fcrYFNaTjcS6g4U3t-Y5bbKic1PW3nceB3q24YFOMg.ttf
MoeNet http://cdn.moefont.com/gstatic/s/materialicons/v12/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2
这个问题会在本周解决，感谢提出

**Comment by cuteSakuraHime** [comment]
您好 请查看一下是否问题已经解决？

**Comment by chiaki64** [comment]
是的 icon能正常显示了.
